# -*- coding: utf-8 -*-
"""Project2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hj76bxFBssTRLRgGwAgDMuu0LdN8sf0c
"""

import pandas as pd

data_df = pd.read_csv('2019_kbo_for_kaggle_v2.csv')
# 2-1
# Print the top 10 players in hits (안타, H), batting average (타율, avg), homerun (홈런, HR),and on base percentage (출루율, OBP) for each year from 2015 to 2018.
#in 2015
data_2015 = data_df[data_df["year"]==2015]
data_2015_h = data_2015.loc[:,['batter_name', 'H']]
data_2015_avg = data_2015.loc[:, ['batter_name', 'avg']]
data_2015_hr = data_2015.loc[:, ['batter_name', 'HR']]
data_2015_obp = data_2015.loc[:, ['batter_name', 'OBP']]
data_2015_h = data_2015_h.sort_values(by='H', ascending=False).head(10)
data_2015_avg = data_2015_avg.sort_values(by='avg', ascending=False).head(10)
data_2015_hr = data_2015_hr.sort_values(by='HR', ascending=False).head(10)
data_2015_obp = data_2015_obp.sort_values(by='OBP', ascending=False).head(10)

#in 2016
data_2016 = data_df[data_df["year"]==2016]
data_2016_h = data_2016.loc[:,['batter_name', 'H']]
data_2016_avg = data_2016.loc[:, ['batter_name', 'avg']]
data_2016_hr = data_2016.loc[:, ['batter_name', 'HR']]
data_2016_obp = data_2016.loc[:, ['batter_name', 'OBP']]
data_2016_h = data_2016_h.sort_values(by='H', ascending=False).head(10)
data_2016_avg = data_2016_avg.sort_values(by='avg', ascending=False).head(10)
data_2016_hr = data_2016_hr.sort_values(by='HR', ascending=False).head(10)
data_2016_obp = data_2016_obp.sort_values(by='OBP', ascending=False).head(10)

#in 2017
data_2017 = data_df[data_df["year"]==2017]
data_2017_h = data_2017.loc[:,['batter_name', 'H']]
data_2017_avg = data_2017.loc[:, ['batter_name', 'avg']]
data_2017_hr = data_2017.loc[:, ['batter_name', 'HR']]
data_2017_obp = data_2017.loc[:, ['batter_name', 'OBP']]
data_2017_h = data_2017_h.sort_values(by='H', ascending=False).head(10)
data_2017_avg = data_2017_avg.sort_values(by='avg', ascending=False).head(10)
data_2017_hr = data_2017_hr.sort_values(by='HR', ascending=False).head(10)
data_2017_obp = data_2017_obp.sort_values(by='OBP', ascending=False).head(10)

#in 2018
data_2018 = data_df[data_df["year"]==2018]
data_2018_h = data_2018.loc[:,['batter_name', 'H']]
data_2018_avg = data_2018.loc[:, ['batter_name', 'avg']]
data_2018_hr = data_2018.loc[:, ['batter_name', 'HR']]
data_2018_obp = data_2018.loc[:, ['batter_name', 'OBP']]
data_2018_h = data_2018_h.sort_values(by='H', ascending=False).head(10)
data_2018_avg = data_2018_avg.sort_values(by='avg', ascending=False).head(10)
data_2018_hr = data_2018_hr.sort_values(by='HR', ascending=False).head(10)
data_2018_obp = data_2018_obp.sort_values(by='OBP', ascending=False).head(10)

#data frame 생성
index = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
data_h = {'2015' : data_2015_h['batter_name'].values, '2016' : data_2016_h['batter_name'].values,
          '2017' : data_2017_h['batter_name'].values, '2018' : data_2018_h['batter_name'].values}
frame_h = pd.DataFrame(data_h, index=index)

data_avg = {'2015' : data_2015_avg['batter_name'].values, '2016' : data_2016_avg['batter_name'].values,
          '2017' : data_2017_avg['batter_name'].values, '2018' : data_2018_avg['batter_name'].values}
frame_avg = pd.DataFrame(data_avg, index=index)

data_hr = {'2015' : data_2015_hr['batter_name'].values, '2016' : data_2016_hr['batter_name'].values,
          '2017' : data_2017_hr['batter_name'].values, '2018' : data_2018_hr['batter_name'].values}
frame_hr = pd.DataFrame(data_hr, index=index)

data_obp = {'2015' : data_2015_obp['batter_name'].values, '2016' : data_2016_obp['batter_name'].values,
          '2017' : data_2017_obp['batter_name'].values, '2018' : data_2018_obp['batter_name'].values}
frame_obp = pd.DataFrame(data_obp, index=index)
#print
print("#2-1")
print("The top 10 players in hits(안타) from 2015 to 2018")
print(frame_h)
print("The top 10 players in batting average(타율) from 2015 to 2018")
print(frame_avg)
print("The top 10 players in homerun(홈런) from 2015 to 2018")
print(frame_hr)
print("The top 10 players in on base percentage(출루율) from 2015 to 2018")
print(frame_obp)

# 2-2
# Print the player with the highest war(승리기여도) by position in 2018
data_2018 = data_df[data_df["year"]==2018]
data_2018_war = data_2018.loc[:,['batter_name', 'war', 'cp']]
data_2018_war = data_2018_war.sort_values(by='war', ascending=False)

data_2018_war_cp0 = data_2018_war[data_2018_war["cp"]=="포수"].head(1)
data_2018_war_cp1 = data_2018_war[data_2018_war["cp"]=="1루수"].head(1)
data_2018_war_cp2 = data_2018_war[data_2018_war["cp"]=="2루수"].head(1)
data_2018_war_cp3 = data_2018_war[data_2018_war["cp"]=="3루수"].head(1)
data_2018_war_cp4 = data_2018_war[data_2018_war["cp"]=="유격수"].head(1)
data_2018_war_cp5 = data_2018_war[data_2018_war["cp"]=="좌익수"].head(1)
data_2018_war_cp6 = data_2018_war[data_2018_war["cp"]=="중견수"].head(1)
data_2018_war_cp7 = data_2018_war[data_2018_war["cp"]=="우익수"].head(1)

data_war = [data_2018_war_cp0['batter_name'].values, data_2018_war_cp1['batter_name'].values,
           data_2018_war_cp2['batter_name'].values, data_2018_war_cp3['batter_name'].values,
          data_2018_war_cp4['batter_name'].values, data_2018_war_cp5['batter_name'].values,
           data_2018_war_cp6['batter_name'].values, data_2018_war_cp7['batter_name'].values]
series_war = pd.Series(data_war)
series_war.index = ['포수', '1루수', '2루수', '3루수', '유격수', '좌익수', '중견수', '우익수']
series_war.name = 'batter_name'
series_war.index.name = 'position'
print("#2-2")
print("The player with the highest war(승리기여도) by position in 2018")
print(series_war)

# 2-3
# Among R(득점), H(안타), HR(홈런), RBI(타점), SB(도루), war(승리기여도), avg(타율), OBP(출루율), and SLG(장타율), which has the highest correlation with salary(연봉)?
data_corr = data_df.loc[:,['R', 'H', 'HR', 'RBI', 'SB', 'war', 'avg', 'OBP', 'SLG', 'salary']]
data_corr = data_corr.corr().loc['salary']
data_corr = data_corr.drop('salary')
data_corr.index = ['R(득점)', 'H(안타)', 'HR(홈런)', 'RBI(타점)', 'SB(도루)', 'war(승리기여도)', 'avg(타율)', 'OBP(출루율)', 'SLG(장타율)']
data_corr = data_corr.sort_values(ascending=False).head(1)
print("#2-3")
print("Among R(득점), H(안타), HR(홈런), RBI(타점), SB(도루), war(승리기여도), avg(타율), OBP(출루율), and SLG(장타율), which has the highest correlation with salary(연봉)?")
print(data_corr.index.values)